### ISSUE TITLE
`spawn` not marking functions as suspendable

### ISSUE THREAD

**Issue by hsgrott** [puniverse/pulsar#46]
Hi,

A call like `(spawn foo)` will mark `foo` as suspendable (as in `(suspendable! foo)`), but a call like `(spawn foo arg1 arg2)` will not. To test:

a) create a new pulsar project (here is a gist: https://gist.github.com/hsgrott/258e419db4a6ea31f76e)
b) run a REPL;
c) call `(suspendable? ping)` and `(suspendable? pong)` in the main ns; both should return `false`;
d) call `(main)`; the function should hang with "Pong received ping" in the standard output;
f) break the execution, call `(suspendable? ping)` and `(suspendable? pong)`; the first should return `false`, the last should return `true`;

Additionally, calling `(suspendable! ping)` will make things work as expected.

The code was tested with Clojure 1.7.0 (Java 1.8.0_66-b17) and Pulsar 0.7.3 on an Ubuntu 15.10 machine (Linux 4.2.0-18-generic #22-Ubuntu SMP x86_64).

Regards.

**Comment by circlespainter** [comment]
Thanks for the very precise report.
