### ISSUE TITLE
Class JavaLaunchHelper is implemented in both .../java and .../libinstrument.dylib

### ISSUE THREAD

**Issue by stig** [puniverse/pulsar#49]
When adding the quasar-core Java agent to my project.clj I get this warning when running Leiningen:

```shell
% lein repl
objc[4600]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
```

This is my project.clj:

```clojure
(defproject pulsar-toy "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [co.paralleluniverse/quasar-core "0.7.3"]
                 [co.paralleluniverse/pulsar "0.7.3"]
                 [org.clojure/tools.logging "0.3.1"]
                 [org.slf4j/slf4j-log4j12 "1.7.12"]
                 [log4j/log4j "1.2.17"]]

  :main ^:skip-aot pulsar-toy.core
  :target-path "target/%s"
  :java-agents [[co.paralleluniverse/quasar-core "0.7.3"]])
```

**Comment by circlespainter** [comment]
It seems to be an annoyance related to a JDK issue that not been fixed yet for 1.8: http://stackoverflow.com/questions/18794573/objc10012-class-javalaunchhelper-is-implemented-in-both-libinstrument-dyl

**Comment by circlespainter** [comment]
I'll close it as there's not much that can be done in Quasar/Pulsar.

**Comment by davoVloom** [comment]
You must go to Preferences/Build, Execution, Deployment/Debugger and disable the option: "Force Classic VM for JDK 1.3.x and earlier" This works for me

**Comment by vryba** [comment]
Proposed solution didn't work for me, still have "...One of the two will be used. Which one is undefined."

**Comment by Rauk** [comment]
Same for me as well, the solution is not working.
Jdk version: jdk1.8.0_131.jdk
Tried running both on Intellij Idea and Eclipse. 
Eclipse is not even showing error and closes the execution without any error.

**Comment by chitraj8** [comment]
I hit the same error - none of the proposed solutions works for me

**Comment by webit4me** [comment]
Disabling "Force Classic VM for JDK 1.3.x and earlier" works fine as @davoVloom described, but only after restart the IDE

**Comment by AvinashGandhasiri** [comment]
Do what @davoVloom and @webit4me says, it worked for me
1) Disable "Force Classic VM for JDK 1.3.x and earlier"
2) Restart IDE
Thanks to both of you

**Comment by felipealvesgnu** [comment]
@vryba It just works in Debug Mode, but in Run Mode it won't in IntelliJ !

**Comment by Tsahao** [comment]
The bug has been solved. Please update your JDK
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8022291
