### ISSUE TITLE
Blocking and bound mailboxes - not working as expected

### ISSUE THREAD

**Issue by markjfisher** [puniverse/pulsar#75]
I may have understood this incorrectly, but when I send messages to an actor that has a bounded sized mailbox with a overflow policy of block, it doesn't appear to block and instead I'm getting QueueCapacityExceededException.

A simple example is:

    (defsfn handler-sfn []
            (loop []
              (receive [m]
                       [:message data] (do (infof "received data: %s" data)
                                           (sleep 50))
                       :else
                       (infof "Unknown message received in handler-sfn - %s" m))
              (recur)))
    
    (defsfn adder-sfn [handler]
            (dorun (for [x (range 100)]
                     (do (infof "sending message %s" x)
                         (! handler [:message x])))))
    
    (defn -main
      []
      (let [handler (spawn :mailbox-size 10 :overflow-policy :block handler-sfn)
            adder   (spawn adder-sfn handler)]
        (join handler)))

If I remove the mailbox-size and overflow-policy, the example works, it sends 100 messages, and receives them all, as does setting the mailbox size to >100 as it doesn't fill up. However, as it stands the sending doesn't block, and the exception is thrown.

What's the correct way to block the sender in this case?

**Comment by pron** [comment]
See puniverse/quasar#283

**Comment by markjfisher** [comment]
Thanks for the response @pron.
