### ISSUE TITLE
register! creates an mbean, need to remove with quasar

### ISSUE THREAD

**Issue by angusiguess** [puniverse/pulsar#76]
When an actor is registered, a quasar actor mbean is created, this mbean remains even after the actor has terminated. On systems that register a large number of actors, this can result in a memory leak.

My current workaround is to use ```LocalActor/stopMonitor``` when deregistering or terminating an actor.

Is there a better practice or, failing that, are there API improvements we can make to clean up reliably?

**Comment by pron** [comment]
Fixed in Quasar.
