### ISSUE TITLE
Status of pulsar

### ISSUE THREAD

**Issue by ulises** [puniverse/pulsar#80]
Is pulsar still being maintained?

**Comment by mrkaspa** [comment]
If it is not is there an alternative?

**Comment by pron** [comment]
I may release a version that uses the new Quasar 0.8.0 with JDK 11 support, but other than that I don't think I'll have the time for further improvements, at least until Loom is released. *Small* patches are welcome.

**Comment by ulises** [comment]
@pron thanks for the update!
